import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import log from 'electron-log'
import { deriveLlamaBackendsFromCapabilities, normalizeLlamaBackend, selectPreferredLlamaBackend } from '../../../shared/ai/llamaBackend.js'
const DEFAULT_MODEL_DIR=path.join(os.homedir(),'.elephantnote','models','node-llama-cpp')
const NODE_LLAMA_CPP_MODULE=['node','llama','cpp'].join('-')
const loadNodeLlamaCpp=async()=>import(/* @vite-ignore */ NODE_LLAMA_CPP_MODULE)
const DEFAULT_EMBEDDING_CONTEXT_SIZE=8192,DEFAULT_CHAT_CONTEXT_SIZE=4096,DEFAULT_LOAD_CONTEXT_SIZE=8192
const BENIGN_NATIVE_WARNING_PREFIXES=['llama_context: n_ctx_seq (','init: embeddings required but some input tokens were not marked as outputs -> overriding']
const normalizeLogText=(v='')=>Array.isArray(v)?v.map(normalizeLogText).filter(Boolean).join(' '):String(v||'').replace(/\s+/g,' ').trim()
const normalizeProgress=({totalSize=0,downloadedSize=0}={})=>{const total=Number(totalSize)||0,downloaded=Number(downloadedSize)||0;return{totalSize:total,downloadedSize:downloaded,percent:total>0?Math.max(0,Math.min(100,Math.round(downloaded/total*100))):0}}
const resolveChatContextSize=(r=0,t=0)=>{const req=Number(r)||0,train=Number(t)||0,cap=train>0?train:DEFAULT_CHAT_CONTEXT_SIZE;return Math.max(1,req>0?Math.max(req,cap):cap)}
const resolveEmbeddingContextSize=(r=0,t=0)=>{const req=Number(r)||0,train=Number(t)||0,cap=train>0?train:DEFAULT_EMBEDDING_CONTEXT_SIZE;return Math.max(1,req>0?Math.max(req,cap):cap)}
const resolveLoadContextSize=(m={})=>{const r=Number(m.contextSize||m.embeddingContextSize)||0;return r>0?Math.max(r,DEFAULT_LOAD_CONTEXT_SIZE):DEFAULT_LOAD_CONTEXT_SIZE}
const isBenignNativeWarning=(m='')=>BENIGN_NATIVE_WARNING_PREFIXES.some(p=>normalizeLogText(m).includes(p))
export const shouldSuppressLlamaLog=(...a)=>isBenignNativeWarning(normalizeLogText(a))
export const createLlamaLogger=(logger=log)=>({log:(...a)=>{if(!shouldSuppressLlamaLog(...a))logger.info(...a)},info:(...a)=>{if(!shouldSuppressLlamaLog(...a))logger.info(...a)},warn:(...a)=>{if(!shouldSuppressLlamaLog(...a))logger.warn(...a)},error:(...a)=>logger.error(...a)})
const resolveDownloadUri=(m={})=>{const raw=String(m.uri||m.modelUri||m.pull||m.model||m.id||m.repoId||'').trim(),file=String(m.fileName||m.filename||'').trim();if(!raw)return'';if(/^(hf:|https?:\/\/|file:)/i.test(raw))return raw;if(raw.includes('/')&&file&&!raw.toLowerCase().endsWith('.gguf'))return`hf:${raw}/${file}`;return raw}
export class NodeLlamaCppRuntime{constructor({modelDir=DEFAULT_MODEL_DIR,moduleLoader=loadNodeLlamaCpp,llamaOptions={},preferredBackends=['cpu','gpu','mpu','npu','openvino','tpu']}={}){this.modelDir=modelDir;this.moduleLoader=moduleLoader;this.llamaOptions={logLevel:'warn',logger:createLlamaLogger(),...llamaOptions};this.preferredBackends=[...preferredBackends];this.loaded=new Map()}
async _resolveCapabilities(){try{const mod=await this.moduleLoader(),gpuTypes=typeof mod.getLlamaGpuTypes==='function'?await mod.getLlamaGpuTypes().catch(()=>[]):[],hasOpenVino=String(this.llamaOptions?.cmakeOptions?.GGML_OPENVINO||'').toUpperCase()==='ON',dev=String(this.llamaOptions?.openvinoDevice||this.llamaOptions?.cmakeOptions?.GGML_OPENVINO_DEVICE||'').trim().toUpperCase(),hasNpu=hasOpenVino&&dev==='NPU',supportedBackends=deriveLlamaBackendsFromCapabilities({gpuTypes,hasOpenVino,hasNpu,runtime:'node'});return{mod,gpuTypes,supportedBackends,selectedBackend:selectPreferredLlamaBackend({availableBackends:supportedBackends,preferredOrder:this.preferredBackends})||'cpu'}}catch(error){return{mod:null,gpuTypes:[],supportedBackends:['cpu'],selectedBackend:'cpu',error}}}
async status(){try{const{mod,gpuTypes,supportedBackends,selectedBackend}=await this._resolveCapabilities(),models=await this.listModels();return{provider:'node-llama-cpp',available:true,modelDir:this.modelDir,gpuTypes,supportedBackends,selectedBackend,preferredBackends:[...this.preferredBackends],version:typeof mod.getModuleVersion==='function'?mod.getModuleVersion():'',models,message:`node-llama-cpp ready on ${selectedBackend}.`}}catch(error){return{provider:'node-llama-cpp',available:false,modelDir:this.modelDir,models:[],message:error instanceof Error?error.message:'node-llama-cpp is not available.'}}}
async listModels(){await fs.mkdir(this.modelDir,{recursive:true});const entries=await fs.readdir(this.modelDir,{withFileTypes:true}).catch(()=>[]);return entries.filter(e=>e.isFile()&&e.name.toLowerCase().endsWith('.gguf')).map(e=>({id:e.name,name:e.name,model:e.name,provider:'node-llama-cpp',path:path.join(this.modelDir,e.name)})).sort((a,b)=>a.name.localeCompare(b.name))}
async resolveModel(model={}, {onProgress}={}){const mod=await this.moduleLoader();await fs.mkdir(this.modelDir,{recursive:true});const uri=resolveDownloadUri(model);if(!uri)throw new Error('node-llama-cpp model URI is required.');return mod.resolveModelFile(uri,{directory:this.modelDir,fileName:model.fileName||model.filename||undefined,download:model.download??'auto',verify:model.verify??false,headers:model.headers||undefined,endpoints:model.endpoints||undefined,tokens:model.tokens||undefined,parallel:model.parallel||undefined,signal:model.signal||undefined,cli:false,onProgress:s=>onProgress?.({id:model.id,modelId:model.id,phase:'downloading',message:`Downloading ${model.name||model.id}...`,...normalizeProgress(s)})})}
async downloadModel(model={},options={}){const startedAt=Date.now(),modelPath=await this.resolveModel(model,options);return{id:model.id,provider:'node-llama-cpp',downloaded:true,modelPath,modelDir:this.modelDir,message:`${model.name||model.id} downloaded for node-llama-cpp in ${Math.max(1,Math.round((Date.now()-startedAt)/1000))}s.`}}
async loadModel(model={}){const modelPath=model.path||await this.resolveModel(model);if(this.loaded.has(modelPath))return this.loaded.get(modelPath);const mod=await this.moduleLoader(),llama=await mod.getLlama(this.llamaOptions),backend=normalizeLlamaBackend(model.backend||'auto'),loadedModel=await llama.loadModel({modelPath,contextSize:resolveLoadContextSize(model),gpuLayers:backend==='cpu'?0:model.gpuLayers??'auto'}),record={mod,model:loadedModel,modelPath};this.loaded.set(modelPath,record);return record}
async unloadModel(model={}){const modelPath=typeof model==='string'?model:model.path||model.modelPath||model.id||'';if(!modelPath)return{provider:'node-llama-cpp',unloaded:false,message:'Model path is required to unload a node-llama-cpp model.'};const record=this.loaded.get(modelPath);if(!record)return{provider:'node-llama-cpp',unloaded:false,modelPath,message:'Model is not currently loaded.'};for(const target of[record.model,record.context,record.session]){if(target?.dispose)await target.dispose().catch(()=>{});if(target?.unload)await target.unload().catch(()=>{})}this.loaded.delete(modelPath);return{provider:'node-llama-cpp',unloaded:true,modelPath,message:'Model unloaded.'}}
async generateChat({model={},messages=[],prompt='',maxTokens=80,temperature=0}={}){const{mod,model:loadedModel}=await this.loadModel(model),context=await loadedModel.createContext({contextSize:resolveChatContextSize(model.contextSize,loadedModel.trainContextSize)});try{const session=new mod.LlamaChatSession({contextSequence:context.getSequence()}),lastUser=prompt||[...messages].reverse().find(m=>m.role==='user')?.content||'';return String(await session.prompt(lastUser,{maxTokens,temperature})||'').trim()}finally{await context.dispose()}}
async embedText({model={},text=''}={}){const{model:loadedModel}=await this.loadModel(model),context=await loadedModel.createEmbeddingContext({contextSize:resolveEmbeddingContextSize(model.embeddingContextSize||model.contextSize,loadedModel.trainContextSize)});try{const embedding=await context.getEmbeddingFor(String(text||''));return Array.from(embedding.vector||[])}finally{await context.dispose()}}
async extractImageText(){throw new Error('node-llama-cpp text bindings are available, but this build does not expose llama.cpp multimodal image input. OCR needs a llama.cpp multimodal server/tool or a dedicated OCR engine.')}
}
