import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

describe('optional editor feature addons', () => {
  it('keeps the base code block in Muya and contributes execution separately', () => {
    const main = read('Elephant/frontend/src/renderer/src/main.js')
    const addon = read('Elephant/frontend/src/renderer/src/addons/builtin/codeExecution.js')
    const settings = read('Elephant/frontend/src/renderer/src/addons/builtin/ui/CodeExecutionSettings.vue')
    const runtime = read('Elephant/frontend/src/renderer/src/platform/executableCodeBlocks.js')
    const lifecycle = read('Elephant/frontend/src/renderer/src/platform/executableCodeNativeLifecycle.js')
    const nativeRuntime = read('Elephant/frontend/src/renderer/src/platform/executableCodeNativeRuntime.js')
    const renderer = read('Elephant/frontend/src/muya/lib/parser/render/renderBlock/renderContainerBlock.js')
    const bridge = read('Elephant/frontend/src/muya/lib/parser/render/renderBlock/editorExtensionRenderBridge.js')
    const backend = read('Elephant/backend/tauri/src/code_execution.rs')
    const customBackend = read('Elephant/backend/tauri/src/code_execution_custom.rs')

    expect(main).not.toContain('installExecutableCodeBlocks')
    expect(addon).toContain("const ADDON_ID = 'elephant.code-execution'")
    expect(addon).toContain('defaultEnabled: false')
    expect(addon).toContain('removable: true')
    expect(addon).toContain('installExecutableCodeBlocks(globalThis)')
    expect(addon).toContain('ctx.addEditorExtension')
    expect(addon).toContain('renderExecutableRunButton(block)')
    expect(addon).toContain("section: 'editor'")
    expect(addon).toContain('setExecutionEnabled(true')
    expect(addon).toContain('setExecutionEnabled(false')
    expect(addon).toContain('runtime?.dispose?.()')
    expect(settings).toContain('Retained output')
    expect(settings).toContain('Add interpreter')
    expect(settings).toContain('customEnvironments')
    expect(settings).toContain('INTERPRETERS_COLLAPSED_KEY')
    expect(settings).toContain('interpretersExpanded')
    expect(settings).toContain("'Hide interpreters'")
    expect(settings).toContain('id="en-code-interpreters-content"')
    expect(runtime).not.toContain('installExecutableCodeSettings')
    expect(runtime).toContain('resetExecutableCodeNativeRuntimeForTests')
    expect(lifecycle).toContain("event.key !== 'Enter'")
    expect(lifecycle).toContain("documentTarget.addEventListener('click'")
    expect(nativeRuntime).toContain("invoke('tauri_programs_list_with_custom')")
    expect(nativeRuntime).toContain("invoke('tauri_programs_run_with_custom'")
    expect(backend).toContain('tauri_programs_list_with_custom')
    expect(backend).toContain('custom::resolve')
    expect(customBackend).toContain('code-execution-custom.json')
    expect(customBackend).toContain('templates_payload')
    expect(customBackend).toContain('MAX_OUTPUT_BYTES')
    expect(customBackend).toContain('VecDeque::with_capacity(MAX_OUTPUT_BYTES)')
    expect(customBackend).not.toContain('read_to_end')
    expect(renderer).toContain('children.unshift(renderCopyButton(t))')
    expect(renderer).not.toContain('renderExecutableRunButton')
    expect(renderer).toContain('applyEditorContainerExtensions')
    expect(bridge).toContain("const EDITOR_EXTENSION_AREA = 'editor.extensions'")
  })

  it('keeps Excalidraw out of every base editor surface and contributes it only while enabled', () => {
    const main = read('Elephant/frontend/src/renderer/src/main.js')
    const addon = read('Elephant/frontend/src/renderer/src/addons/builtin/excalidraw.js')
    const builtins = read('Elephant/frontend/src/renderer/src/addons/builtin/index.js')
    const addonIcon = read('Elephant/frontend/app/components/settings/AddonIcon.vue')
    const excalidrawMark = read('Elephant/frontend/app/components/settings/ExcalidrawMark.vue')
    const toolbar = read('Elephant/frontend/src/muya/lib/ui/imageToolbar/index.js')
    const toolbarStyles = read('Elephant/frontend/src/muya/lib/ui/imageToolbar/index.css')
    const toolbarConfig = read('Elephant/frontend/src/muya/lib/ui/imageToolbar/config.js')
    const quickInsert = read('Elephant/frontend/src/muya/lib/ui/quickInsert/config.js')
    const writingBridge = read('Elephant/frontend/src/renderer/src/platform/writingCommandBridge.js')
    const bridge = read('Elephant/frontend/src/muya/lib/parser/render/renderBlock/editorExtensionRenderBridge.js')
    const markdown = read('Elephant/frontend/src/renderer/src/platform/excalidrawMarkdownCleanup.js')
    const images = read('Elephant/frontend/src/renderer/src/platform/excalidrawImageRuntimeFixes.js')
    const fallbacks = read('Elephant/frontend/src/renderer/src/addons/addonContentFallbackRuntime.js')
    const manifest = read('Elephant/frontend/src/renderer/src/addons/manifest.js')

    expect(main).not.toContain('installExcalidrawMarkdownCleanup')
    expect(main).not.toContain('installExcalidrawImageRuntimeFixes')
    expect(toolbarConfig).not.toContain('Excalidraw')
    expect(toolbar).not.toContain('edit-excalidraw')
    expect(toolbar).toContain('getEditorImageToolbarItems')
    expect(quickInsert).not.toContain("title: 'Excalidraw'")
    expect(quickInsert).not.toContain('elephant-command excalidraw')
    expect(quickInsert).toContain('addonQuickInsertItems')
    expect(writingBridge).not.toContain("case 'excalidraw':")
    expect(writingBridge).toContain('addonWritingCommands')
    expect(bridge).toContain('imageToolbarItems')
    expect(addon).toContain("const ADDON_ID = 'elephant.excalidraw'")
    expect(addon).toContain('defaultEnabled: false')
    expect(addon).toContain("icon: 'excalidraw'")
    expect(addon).toContain('EXCALIDRAW_ICON')
    expect(addon).toContain('installExcalidrawMarkdownCleanup()')
    expect(addon).toContain('installExcalidrawImageRuntimeFixes(globalThis)')
    expect(addon).toContain('imageToolbarItems: [{')
    expect(addon).toContain('quickInsertItems: [{')
    expect(addon).toContain("commandId: 'excalidraw'")
    expect(addon).toContain("id: 'edit-drawing'")
    expect(addon).toContain('contentTypes: [{')
    expect(addon).toContain("disabledPresentation: 'static-preview'")
    expect(addonIcon).toContain('excalidraw: ExcalidrawMark')
    expect(excalidrawMark).toContain('viewBox="0 0 40 40"')
    expect(excalidrawMark).toContain('fill="currentColor"')
    expect(excalidrawMark).toContain('M39.9 32.889')
    expect(toolbarStyles).toContain('.icon-inner')
    expect(toolbarStyles).toContain('background-size: contain !important')
    expect(builtins).toContain("load: () => import('./excalidraw')")
    expect(builtins).not.toContain("import { excalidrawAddon } from './excalidraw'")
    expect(markdown).toContain('unsubscribe?.()')
    expect(markdown).toContain("bus.off?.('invalidate-image-cache'")
    expect(images).toContain('observer.disconnect()')
    expect(images).toContain("document.removeEventListener('load'")
    expect(images).toContain('removeInstalledUi()')
    expect(fallbacks).toContain('collectDescriptors')
    expect(fallbacks).toContain('isCurrentFallback')
    expect(fallbacks).toContain('blockDisabledInteraction')
    expect(fallbacks).toContain("'Optional content unavailable'")
    expect(manifest).toContain('contributes.contentTypes')
  })

  it('groups AI capability addons under the AI parent in addon management', () => {
    const builtins = read('Elephant/frontend/src/renderer/src/addons/builtin/index.js')
    const panel = read('Elephant/frontend/app/components/settings/AddonsSettingsPanel.vue')

    expect(builtins).toContain("name: 'AI'")
    expect(builtins).not.toContain("name: 'AI Providers'")
    expect(builtins.match(/parentAddonId: 'elephant\.ai'/g)).toHaveLength(5)
    expect(panel).toContain('const GROUPED_ADDON_IDS = new Set(AI_SUBMODULE_IDS)')
    expect(panel).toContain('class="en-ai-module-list"')
    expect(panel).toContain('installAiModule(module)')
  })

  it('includes editor and sidebar addons in the refreshed first-party packs', () => {
    const packs = read('Elephant/frontend/src/renderer/src/addons/builtin/addonProfiles.js')

    expect(packs).toContain("id: 'elephant.code-execution'")
    expect(packs).toContain("id: 'elephant.excalidraw'")
    expect(packs).toContain("id: 'elephant.recently-edited'")
    expect(packs).toContain("const BASE_PACK_PATH = `${PACK_DIRECTORY}/base.enaddonpack`")
    expect(packs).toContain(".filter((entry) => entry.id !== 'elephant.calendar')")
    expect(packs).toContain("name: 'ElephantNote Base'")
    expect(packs).toContain('ensureBasePack')
    expect(packs).toContain('isDevelopParityCurrent')
    expect(packs).toContain('Missing, invalid or stale protected packs are regenerated below.')
  })
})
