import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

describe('Sync physical migration boundary', () => {
  it('owns the persistent Iroh endpoint and stable identity in a package service', () => {
    const manifest = JSON.parse(read('addons/official/sync/manifest.json'))
    const build = JSON.parse(read('addons/official/sync/addon.build.json'))
    const native = read('addons/official/sync/native/src/main.rs')

    expect(manifest.native.runner).toBe('service')
    expect(manifest.native.protocol).toBe('elephant-addon-service-v1')
    expect(build.runner).toBe('service')
    expect(native).toContain('Endpoint::builder(presets::Minimal)')
    expect(native).toContain('.secret_key(secret_key)')
    expect(native).toContain('.address_lookup(MdnsAddressLookup::builder().service_name(MDNS_SERVICE))')
    expect(native).toContain('load_or_create_secret_key')
    expect(native).toContain('wait_for_endpoint_addr')
    expect(native).toContain('sync.endpoint')
  })

  it('runs active pairing and synchronization through the package while keeping legacy core code only as removable compatibility residue', () => {
    const manifest = JSON.parse(read('addons/official/sync/manifest.json'))
    const entry = read('addons/official/sync/main.service.js')
    const native = read('addons/official/sync/native/src/main.rs')
    const nativeLibrary = read('addons/official/sync/native/src/lib.rs')
    const invite = read('addons/official/sync/native/src/invite.rs')
    const pairing = read('addons/official/sync/native/src/pairing.rs')
    const protocol = read('addons/official/sync/native/src/protocol.rs')
    const session = read('addons/official/sync/native/src/session.rs')
    const transfer = read('addons/official/sync/native/src/transfer.rs')
    const legacyEntry = read('addons/official/sync/main.js')
    const core = read('Elephant/backend/tauri/src/lib_min.rs')
    const coreRuntime = read('Elephant/backend/tauri/src/sync/mod.rs')
    const coreNetwork = read('Elephant/backend/tauri/src/vault/sync_iroh/network.rs')

    expect(manifest.description).toContain('vault manifest scanning and deterministic sync planning')
    expect(entry).toContain("from './main.js'")
    expect(entry).toContain("this.callNativeService('sync.create-invite'")
    expect(entry).toContain("this.callNativeService('sync.accept-invite'")
    expect(entry).toContain("this.callNativeService('sync.run'")
    expect(entry).toContain("if (command === 'iroh_sync_run') return await this.runNativeSync()")
    expect(entry).toContain("if (command === 'iroh_sync_create_invite')")
    expect(entry).toContain("if (command === 'iroh_sync_accept_invite')")
    expect(native).toContain('use elephant_sync_service::{')
    expect(native).toContain('Router::builder(endpoint.clone())')
    expect(native).toContain('SyncProtocol')
    expect(native).toContain('handle_incoming_connection')
    expect(native).toContain('ControlMessage::SyncOpen(open)')
    expect(native).toContain('serve_sync_session(')
    expect(native).toContain('run_all_sessions(&endpoint, &self.vault_dir)')
    expect(native).toContain('"sync.run" => service.run_sync().await')
    expect(native).toContain('"networkTransfersReady": true')
    expect(nativeLibrary).toContain('pub mod invite;')
    expect(nativeLibrary).toContain('pub mod pairing;')
    expect(nativeLibrary).toContain('pub mod protocol;')
    expect(nativeLibrary).toContain('pub mod session;')
    expect(nativeLibrary).toContain('pub mod transfer;')
    expect(invite).toContain('pub struct PairingInvite')
    expect(invite).toContain('pub fn verify_pending_invite')
    expect(pairing).toContain('pub struct SyncConfig')
    expect(pairing).toContain('pub fn create_pending_invite')
    expect(pairing).toContain('pub fn consume_pair_request')
    expect(pairing).toContain('pub fn register_accepted_peer')
    expect(protocol).toContain('pub const ALPN: &[u8] = b"elephantnote/vault-sync/1"')
    expect(protocol).toContain('pub enum ControlMessage')
    expect(protocol).toContain('PairRequest(PairRequest)')
    expect(protocol).toContain('SyncOpen(SyncOpen)')
    expect(session).toContain('pub async fn run_all_sessions')
    expect(session).toContain('pub async fn serve_sync_session')
    expect(transfer).toContain('pub async fn send_file')
    expect(transfer).toContain('pub async fn receive_file')

    // These files still exist temporarily, but the package entry intercepts every active UI command.
    expect(legacyEntry).toContain("this.invoke('iroh_sync_run'")
    expect(core).toContain('sync_commands::iroh_sync_run')
    expect(coreRuntime).toContain('.accept(protocol::ALPN, VaultSyncProtocol { app })')
    expect(coreRuntime).toContain('struct VaultSyncProtocol')
    expect(coreNetwork).toContain('pub async fn sync_create_invite')
    expect(coreNetwork).toContain('pub async fn sync_accept_invite')
  })

  it('keeps mobile unsupported until a real package-owned host exists', () => {
    const manifest = JSON.parse(read('addons/official/sync/manifest.json'))
    expect(manifest.native.mobile.android.supported).toBe(false)
    expect(manifest.native.mobile.ios.supported).toBe(false)
    expect(manifest.native.mobile.android.reason).toContain('mobile Sync host adapter')
    expect(manifest.native.mobile.ios.reason).toContain('mobile Sync host adapter')
  })
})
