import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

describe('physical Sync package ownership', () => {
  it('owns identity, pairing, wire schema, file streams, manifests, planning and local operations inside the native package', () => {
    const service = read('addons/official/sync/native/src/main.rs')
    const library = read('addons/official/sync/native/src/lib.rs')
    const invite = read('addons/official/sync/native/src/invite.rs')
    const pairing = read('addons/official/sync/native/src/pairing.rs')
    const protocol = read('addons/official/sync/native/src/protocol.rs')
    const transfer = read('addons/official/sync/native/src/transfer.rs')
    const manifest = read('addons/official/sync/native/src/manifest.rs')
    const plan = read('addons/official/sync/native/src/plan.rs')
    const localOps = read('addons/official/sync/native/src/local_ops.rs')

    expect(service).toContain('use elephant_sync_service::{')
    expect(service).toContain('Router::builder(endpoint.clone())')
    expect(service).toContain('.accept(')
    expect(service).toContain('PairingProtocol')
    expect(service).toContain('load_or_create_secret_key')
    expect(service).toContain('"sync.create-invite" => service.create_invite(params).await')
    expect(service).toContain('"sync.accept-invite" => service.accept_invite(params).await')
    expect(service).toContain('"sync.scan" => service.scan()')
    expect(service).toContain('"sync.plan" => service.plan(params).await')
    expect(service).toContain('"sync.apply-local" => service.apply_local(params)')
    expect(service).toContain('"networkTransfersReady": false')
    expect(service).toContain('"wire-protocol"')
    expect(service).toContain('"pairing"')

    expect(library).toContain('pub mod invite;')
    expect(library).toContain('pub mod pairing;')
    expect(library).toContain('pub mod protocol;')
    expect(library).toContain('pub mod transfer;')
    expect(invite).toContain('pub struct PendingInvite')
    expect(invite).toContain('pub struct PairingInvite')
    expect(invite).toContain('pub fn verify_pending_invite')
    expect(pairing).toContain('pub struct SyncConfig')
    expect(pairing).toContain('pub fn create_pending_invite')
    expect(pairing).toContain('pub fn consume_pair_request')
    expect(pairing).toContain('pub fn register_accepted_peer')
    expect(pairing).toContain('Pairing invite is invalid, expired or already used')
    expect(protocol).toContain('pub const ALPN: &[u8] = b"elephantnote/vault-sync/1"')
    expect(protocol).toContain('pub enum ControlMessage')
    expect(protocol).toContain('PairRequest(PairRequest)')
    expect(protocol).toContain('SyncComplete')
    expect(protocol).toContain('pub async fn write_control')
    expect(protocol).toContain('pub async fn read_control')
    expect(transfer).toContain('pub async fn send_file')
    expect(transfer).toContain('pub async fn receive_file')
    expect(transfer).toContain('pub fn validate_header')
    expect(transfer).toContain('ensure_no_symlink_ancestors')
    expect(transfer).toContain('.create_new(true)')
    expect(transfer).toContain('file.sync_all().await')
    expect(transfer).toContain('hash_file(&temporary)')
    expect(manifest).toContain('pub fn scan_vault')
    expect(manifest).toContain('path_is_or_is_below(&normalized, ".elephantnote/addons")')
    expect(plan).toContain('pub fn build_plan')
    expect(plan).toContain('plan_conflict')
    expect(localOps).toContain('pub fn apply_local_plan')
    expect(localOps).toContain('delete_empty_directories')
  })

  it('publishes package-owned pairing and planning methods through the trusted service resource', () => {
    const bridge = read('addons/official/sync/main.service.js')
    const manifest = read('addons/official/sync/manifest.json')

    expect(bridge).toContain("this.callNativeService('sync.create-invite'")
    expect(bridge).toContain("this.callNativeService('sync.accept-invite'")
    expect(bridge).toContain("this.callNativeService('sync.scan'")
    expect(bridge).toContain("this.callNativeService('sync.plan'")
    expect(bridge).toContain("this.callNativeService('sync.apply-local'")
    expect(bridge).toContain("'wire-protocol'")
    expect(bridge).toContain("'pairing'")
    expect(manifest).toContain('"runner": "service"')
    expect(manifest).toContain('"protocol": "elephant-addon-service-v1"')
  })
})
