import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')
const exists = (relativePath) => fs.existsSync(path.join(root, relativePath))
const readSettings = () => read('Elephant/frontend/app/components/settings/SettingsPanel.vue')
const readSettingsStyles = () => read('Elephant/frontend/app/components/settings/settings-redesign.css')
const readSettingsPrimitives = () => read('Elephant/frontend/app/components/settings/settings-primitives.css')
const readSync = () => read('Elephant/frontend/app/components/settings/SyncSettingsPanel.vue')
const readAi = () => read('Elephant/frontend/app/components/settings/AiProviderSettingsPanel.vue')
const readAddons = () => read('Elephant/frontend/app/components/settings/AddonsSettingsPanel.vue')
const readAddonLogic = () => read('Elephant/frontend/app/components/settings/useAddonsSettings.js')
const readAddonStyles = () => read('Elephant/frontend/app/components/settings/addons-settings.css')
const readAddonRow = () => read('Elephant/frontend/app/components/settings/AddonSettingsRow.vue')
const readAddonStore = () => read('Elephant/frontend/src/renderer/src/store/addons.js')
const readAppShell = () => read('Elephant/frontend/app/components/shell/AppShell.vue')
const readMainContent = () => read('Elephant/frontend/app/components/shell/MainContent.vue')
const readIconRail = () => read('Elephant/frontend/app/components/navigation/IconRail.vue')
const readRouter = () => read('Elephant/frontend/src/renderer/src/router/index.js')
const readPreferences = () => read('Elephant/frontend/src/renderer/src/store/preferences.js')
const readBuiltinIndex = () => read('Elephant/frontend/src/renderer/src/addons/builtin/index.js')
const readImportAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/googleKeepImport.js')
const readSitesAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/sites.js')
const readCodexAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/codexConnection.js')
const readAiAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ai.js')
const readSyncAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/sync.js')
const readImportSettings = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ui/ImportSettings.vue')
const readSitesSettings = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ui/SitesSettings.vue')
const readCodexSettings = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ui/CodexConnectionSettings.vue')

describe('ElephantNote settings redesign', () => {
  it('keeps the floating scene with theme-aware blur and native platform chrome', () => {
    const source = readSettings()
    const styles = readSettingsStyles()

    expect(source).toContain('class="en-settings-backdrop"')
    expect(source).toContain('class="en-settings-panel"')
    expect(source).toContain("'is-macos': isMacOS")
    expect(source).toContain('aria-modal="true"')
    expect(source).not.toContain('en-settings-app-mark')
    expect(styles).toContain('backdrop-filter: blur(30px)')
    expect(styles).toContain('var(--en-primary')
    expect(styles).toContain('grid-template-areas: "close title search"')
  })

  it('searches core and installed addon-contributed settings without legacy catalogue labels', () => {
    const source = readSettings()

    expect(source).toContain('placeholder="Search all settings"')
    expect(source).toContain('const settingsIndex = computed')
    expect(source).toContain("label: 'Quick insert trigger'")
    expect(source).toContain("label: 'Installed addons'")
    expect(source).toContain("label: 'Addon packs'")
    expect(source).not.toContain("label: 'Built-in addon catalogue'")
    expect(source).toContain("addonsStore.getContributions('settings.sections')")
    expect(source).toContain('const openSearchResult = (result) =>')
  })

  it('opens a requested section through the active modal instead of a legacy route', () => {
    const settings = readSettings()
    const shell = readAppShell()

    expect(shell).toContain(':initial-section="settingsInitialSection"')
    expect(shell).toContain("window.addEventListener('elephantnote:open-settings', handleOpenSettingsEvent)")
    expect(settings).toContain("initialSection: { type: String, default: 'appearance' }")
    expect(settings).toContain('const normalizeSection = (section) =>')
    expect(settings).toContain('const activeSection = ref(normalizeSection(props.initialSection))')
    expect(settings).toContain('watch(() => props.initialSection')
  })

  it('keeps only indispensable settings in core and restores optional pages through addons', () => {
    const settings = readSettings()
    const builtins = readBuiltinIndex()
    const importAddon = readImportAddon()
    const sitesAddon = readSitesAddon()
    const codexAddon = readCodexAddon()
    const aiAddon = readAiAddon()
    const syncAddon = readSyncAddon()

    expect(settings).toContain("{ id: 'addons', label: 'Addons', icon: Package }")
    expect(settings).not.toContain("{ id: 'sync', label: 'Sync', icon: Cloud }")
    expect(settings).not.toContain("{ id: 'ai', label: 'AI', icon: Sparkles }")
    expect(settings).not.toContain("{ id: 'sites', label: 'Sites', icon: Globe2 }")
    expect(settings).not.toContain("{ id: 'import', label: 'Import', icon: Download }")
    expect(settings).toContain('addonStandaloneSections')
    expect(importAddon).toContain("section: 'import'")
    expect(importAddon).toContain('standalone: true')
    expect(sitesAddon).toContain("section: 'sites'")
    expect(sitesAddon).toContain('standalone: true')
    expect(aiAddon).toContain("section: 'ai'")
    expect(aiAddon).toContain('standalone: true')
    expect(syncAddon).toContain("section: 'sync'")
    expect(syncAddon).toContain('standalone: true')
    expect(codexAddon).toContain("slot: 'ai.providers.after-external'")
    expect(codexAddon).not.toContain('standalone: true')
    expect(builtins).toContain('recentlyEditedAddon')
    expect(builtins).not.toContain('dailyNotesAddon')
    expect(builtins).not.toContain('quickCaptureAddon')
    expect(builtins).not.toContain('vaultOverviewAddon')
    expect(builtins).not.toContain('addonInspectorAddon')
  })

  it('uses one compact community checkbox and the normal addon switch for all access levels', () => {
    const settings = readSettings()
    const addons = readAddons()
    const logic = readAddonLogic()
    const row = readAddonRow()

    expect(settings).toContain('id="en-addons-title-actions"')
    expect(addons).toContain('<Teleport defer to="#en-addons-title-actions">')
    expect(addons).toContain('role="checkbox"')
    expect(addons).toContain(':aria-checked="communityAddonsEnabled"')
    expect(addons).toContain('@click="toggleCommunityAddons"')
    expect(logic).toContain('setCommunityAddonsEnabled(true)')
    expect(logic).toContain('setCommunityAddonsEnabled(false)')
    expect(logic).toContain('const clearMessage = () =>')
    expect(logic).not.toContain("showMessage('Community addons enabled.')")
    expect(logic).not.toContain("showMessage('Community addons disabled.')")
    expect(addons).not.toContain('v-model="riskAccepted"')
    expect(addons).not.toContain('Full app access safe mode')
    expect(addons).not.toContain('Grant access and enable')
    expect(row).not.toContain('Review and grant full app access')
    expect(logic).toContain('approveTrustedAddon(addon.manifest.id)')
    expect(logic).toContain('setTrustedSafeMode(false)')
  })

  it('integrates installed and available addons into one active settings panel', () => {
    const settings = readSettings()
    const addons = readAddons()
    const logic = readAddonLogic()
    const row = readAddonRow()

    expect(settings).toContain("activeSection === 'addons'")
    expect(settings).toContain('<addons-settings-panel />')
    expect(settings).toContain("import AddonsSettingsPanel from './AddonsSettingsPanel.vue'")
    expect(addons).toContain('v-if="filteredInstalledAddons.length || query"')
    expect(addons).toContain('Available addons')
    expect(addons).not.toContain('No optional addon is installed.')
    expect(addons).not.toContain('<h3>Built-in addon catalogue</h3>')
    expect(addons).toContain('<AddonIcon :name="addon.icon"')
    expect(logic).toContain('getAddonActions(contributions.value)')
    expect(logic).toContain('installBuiltin(addon.id)')
    expect(logic).toContain('uninstallBuiltin(addon.manifest.id)')
    expect(logic).toContain('installExternalAddon(selected)')
    expect(logic).toContain('setAddonEnabled(addon.manifest.id')
    expect(addons).toContain('<addon-settings-row')
    expect(row).toContain('role="switch"')
    expect(row).not.toContain('Built in by ElephantNote')
  })

  it('uses inline destructive confirmation and supports removable built-ins', () => {
    const addons = readAddons()
    const logic = readAddonLogic()
    const row = readAddonRow()

    expect(addons).not.toContain('window.confirm')
    expect(logic).not.toContain('window.confirm')
    expect(row).not.toContain('window.confirm')
    expect(row).toContain('confirmingUninstall')
    expect(row).toContain("isExternal.value ? 'Uninstall' : 'Remove'")
    expect(row).toContain('addon.manifest.removable !== false')
  })

  it('refreshes the real vault and opens notes produced by addon commands', () => {
    const store = readAddonStore()

    expect(store).toContain('refreshVaultAfterAddonAction')
    expect(store).toContain("import('elephant-front/stores/vaultStore')")
    expect(store).toContain("import('elephant-front/services/elephantnoteClient')")
    expect(store).toContain("elephantnoteClient.directory.list('')")
    expect(store).toContain('vaultStore.openNote(createdEntry)')
    expect(store).toContain("'[addons] action:start'")
    expect(store).toContain("'[addons] action:done'")
  })

  it('removes the dead legacy Addons settings route and component', () => {
    const router = readRouter()

    expect(router).not.toContain("import AddonsSettings from '@/prefComponents/addons'")
    expect(router).not.toContain("path: 'addons'")
    expect(exists('Elephant/frontend/src/renderer/src/prefComponents/addons/index.vue')).toBe(false)
  })

  it('uses semantic controls and exposes real quick-insert preferences', () => {
    const source = readSettings()
    const preferences = readPreferences()
    const sites = readSitesSettings()

    expect(source).toContain('role="switch"')
    expect(source).toContain(':aria-checked="preferences.showEditorFooter"')
    expect(source).toContain(':aria-checked="!preferences.hideQuickInsertHint"')
    expect(source).toContain("setPreference('quickInsertTrigger'")
    expect(source).toContain("setPreference('autoPairBracket'")
    expect(source).toContain("setPreference('spellcheckerEnabled'")
    expect(sites).toContain(':aria-checked="featureEnabled"')
    expect(preferences).toContain('hideQuickInsertHint: false')
    expect(preferences).toContain("quickInsertTrigger: '/'")
    expect(preferences).toContain('autoPairBracket: true')
  })

  it('collapses Theme and the icon bar without redundant descriptions', () => {
    const source = readSettings()
    const organizer = read('Elephant/frontend/app/components/settings/IconRailLayoutSettings.vue')

    expect(source).toContain('themeExpanded = !themeExpanded')
    expect(source).not.toContain('Choose the visual family used throughout ElephantNote.')
    expect(source).not.toContain('Reorder or hide native features and enabled addon workspaces.')
    expect(organizer).toContain('collapsed = !collapsed')
    expect(organizer).not.toContain('Drag items or use the arrow buttons.')
    expect(organizer).toContain('addDivider')
  })

  it('imports one shared visual primitive layer for AI, Sync and Addons', () => {
    const styles = readSettingsStyles()
    const primitives = readSettingsPrimitives()
    const addons = readAddons()
    const addonStyles = readAddonStyles()
    const row = readAddonRow()

    expect(styles).toContain("@import './settings-primitives.css';")
    expect(primitives).toContain('--en-ui-control-height: 34px')
    expect(primitives).toContain('--en-ui-card-radius: 14px')
    expect(primitives).toContain(':where(.en-ai-card, .en-sync-card, .en-addons-card)')
    expect(primitives).toContain('.en-addons-panel .en-primary-button')
    expect(primitives).toContain('.en-addons-panel .en-switch')
    expect(addons).toContain('<style scoped src="./addons-settings.css"></style>')
    expect(addonStyles).not.toContain('.en-addons-mode-row .en-switch {')
    expect(row).not.toContain('.en-switch {')
  })

  it('preserves the exact Import and Sites page structure after extraction', () => {
    const settings = readSettings()
    const imports = readImportSettings()
    const sites = readSitesSettings()
    const importAddon = readImportAddon()
    const sitesAddon = readSitesAddon()

    expect(settings).not.toContain('await elephantnoteClient.imports.googleKeep()')
    expect(settings).not.toContain("toggleFeature('sitePreview')")
    expect(imports).toContain('<section class="en-settings-group">')
    expect(imports).toContain('await elephantnoteClient.imports.googleKeep()')
    expect(imports).toContain('await elephantnoteClient.sources.ingestUrl')
    expect(imports).toContain('await elephantnoteClient.sources.importRss')
    expect(sites).toContain('<section class="en-settings-group">')
    expect(sites).toContain("elephantnoteClient.features.set('sitePreview'")
    expect(sites).toContain('sitePreviewStore.openPreviewExternal')
    expect(sites).toContain('sitePreviewStore.stopPreview()')
    expect(importAddon).toContain('chrome: false')
    expect(sitesAddon).toContain('chrome: false')
  })

  it('keeps Sync navigation and Codex provider integration addon-owned', () => {
    const sync = readSync()
    const syncAddon = readSyncAddon()
    const ai = readAi()
    const codex = readCodexSettings()
    const codexAddon = readCodexAddon()

    expect(sync).toContain('class="en-sync-toolbar"')
    expect(sync).toContain('v-model.number="retentionDays"')
    expect(syncAddon).toContain("ctx.registerContribution('top-bar.items'")
    expect(ai).toContain("addonsStore.getContributions('ai.providers')")
    expect(ai).toContain('data-elephant-addon-settings-slot="ai.providers.after-external"')
    expect(codex).toContain('<ChatgptSubscriptionCard')
    expect(codex).toContain("invokeCodex('status')")
    expect(codexAddon).toContain("ctx.registerContribution('ai.providers'")
    expect(codexAddon).toContain("slot: 'ai.providers.after-external'")
  })

  it('removes every AI shell element when the addon is absent', () => {
    const addon = readAiAddon()
    const shell = readAppShell()
    const main = readMainContent()
    const rail = readIconRail()

    expect(addon).toContain("id: `${ADDON_ID}.wiki`")
    expect(addon).toContain("id: `${ADDON_ID}.graph`")
    expect(addon).toContain("id: `${ADDON_ID}.models`")
    expect(addon).toContain('store.chatSidebarOpen = false')
    expect(shell).toContain('aiAddonEnabled && store.chatSidebarOpen')
    expect(main).not.toContain('<chat-view')
    expect(main).not.toContain('<models-view')
    expect(main).not.toContain('<wiki-view')
    expect(main).not.toContain('<atomic-graph-view')
    expect(rail).not.toContain("{ id: 'models'")
    expect(rail).not.toContain("{ id: 'chat'")
    expect(rail).not.toContain("{ id: 'wiki'")
    expect(rail).not.toContain("{ id: 'graph'")
  })
})
