import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')
const exists = (relativePath) => fs.existsSync(path.join(root, relativePath))
const readSettings = () => read('Elephant/frontend/app/components/settings/SettingsPanel.vue')
const readSettingsStyles = () => read('Elephant/frontend/app/components/settings/settings-redesign.css')
const readSettingsPrimitives = () => read('Elephant/frontend/app/components/settings/settings-primitives.css')
const readSync = () => read('Elephant/frontend/app/components/settings/SyncSettingsPanel.vue')
const readAi = () => read('Elephant/frontend/app/components/settings/AiProviderSettingsPanel.vue')
const readAddons = () => read('Elephant/frontend/app/components/settings/AddonsSettingsPanel.vue')
const readAddonLogic = () => read('Elephant/frontend/app/components/settings/useAddonsSettings.js')
const readAddonStyles = () => read('Elephant/frontend/app/components/settings/addons-settings.css')
const readAddonRow = () => read('Elephant/frontend/app/components/settings/AddonSettingsRow.vue')
const readAddonStore = () => read('Elephant/frontend/src/renderer/src/store/addons.js')
const readAppShell = () => read('Elephant/frontend/app/components/shell/AppShell.vue')
const readRouter = () => read('Elephant/frontend/src/renderer/src/router/index.js')
const readPreferences = () => read('Elephant/frontend/src/renderer/src/store/preferences.js')
const readBuiltinIndex = () => read('Elephant/frontend/src/renderer/src/addons/builtin/index.js')
const readImportAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/googleKeepImport.js')
const readSitesAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/sites.js')
const readCodexAddon = () => read('Elephant/frontend/src/renderer/src/addons/builtin/codexConnection.js')
const readImportSettings = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ui/ImportSettings.vue')
const readSitesSettings = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ui/SitesSettings.vue')
const readCodexSettings = () => read('Elephant/frontend/src/renderer/src/addons/builtin/ui/CodexConnectionSettings.vue')


describe('ElephantNote settings redesign', () => {
  it('keeps the floating scene with theme-aware blur and native platform chrome', () => {
    const source = readSettings()
    const styles = readSettingsStyles()

    expect(source).toContain('class="en-settings-backdrop"')
    expect(source).toContain('class="en-settings-panel"')
    expect(source).toContain("'is-macos': isMacOS")
    expect(source).toContain('aria-modal="true"')
    expect(source).not.toContain('en-settings-app-mark')
    expect(styles).toContain('backdrop-filter: blur(30px)')
    expect(styles).toContain('var(--en-primary')
    expect(styles).toContain('grid-template-areas: "close title search"')
  })

  it('searches core and addon-contributed settings and opens nested pages', () => {
    const source = readSettings()

    expect(source).toContain('placeholder="Search all settings"')
    expect(source).toContain('const settingsIndex = computed')
    expect(source).toContain("label: 'Quick insert trigger'")
    expect(source).toContain("label: 'Installed addons'")
    expect(source).toContain("label: 'Conflict retention'")
    expect(source).toContain("label: 'Semantic search and embeddings'")
    expect(source).toContain("addonsStore.getContributions('settings.sections')")
    expect(source).toContain('const openSearchResult = (result) =>')
    expect(source).toContain('syncInitialPage.value = result.subpage')
    expect(source).toContain('aiInitialPage.value = result.subpage')
  })

  it('opens a requested section through the active modal instead of a legacy route', () => {
    const settings = readSettings()
    const shell = readAppShell()

    expect(shell).toContain(':initial-section="settingsInitialSection"')
    expect(shell).toContain("window.addEventListener('elephantnote:open-settings', handleOpenSettingsEvent)")
    expect(settings).toContain("initialSection: { type: String, default: 'appearance' }")
    expect(settings).toContain('const normalizeSection = (section) =>')
    expect(settings).toContain('const activeSection = ref(normalizeSection(props.initialSection))')
    expect(settings).toContain("watch(() => props.initialSection")
  })

  it('keeps only core settings in vanilla navigation and restores optional pages through addons', () => {
    const settings = readSettings()
    const builtins = readBuiltinIndex()
    const importAddon = readImportAddon()
    const sitesAddon = readSitesAddon()
    const codexAddon = readCodexAddon()

    expect(settings).toContain("{ id: 'addons', label: 'Addons', icon: Package }")
    expect(settings).not.toContain("{ id: 'sites', label: 'Sites', icon: Globe2 }")
    expect(settings).not.toContain("{ id: 'import', label: 'Import', icon: Download }")
    expect(settings).toContain('addonStandaloneSections')
    expect(importAddon).toContain("section: 'import'")
    expect(importAddon).toContain('standalone: true')
    expect(sitesAddon).toContain("section: 'sites'")
    expect(sitesAddon).toContain('standalone: true')
    expect(codexAddon).toContain("section: 'ai'")
    expect(codexAddon).toContain("slot: 'ai.providers.after-external'")
    expect(codexAddon).not.toContain("section: 'codex'")
    expect(codexAddon).not.toContain('standalone: true')
    expect(builtins.indexOf('addonPacksAddon')).toBeLessThan(builtins.indexOf('googleKeepImportAddon'))
    expect(builtins.indexOf('googleKeepImportAddon')).toBeLessThan(builtins.indexOf('codexConnectionAddon'))
    expect(builtins.indexOf('codexConnectionAddon')).toBeLessThan(builtins.indexOf('calendarAddon'))
    expect(builtins.indexOf('calendarAddon')).toBeLessThan(builtins.indexOf('sitesAddon'))
  })

  it('uses one consent gate and the normal addon switch for all access levels', () => {
    const addons = readAddons()
    const logic = readAddonLogic()
    const row = readAddonRow()

    expect(addons).toContain('v-else-if="!communityAddonsEnabled"')
    expect(addons).toContain('Turn on community addons')
    expect(addons).toContain('v-model="riskAccepted"')
    expect(logic).toContain('setCommunityAddonsEnabled(true)')
    expect(addons).toContain('<template v-else>')
    expect(addons).not.toContain('pendingTrustedAddon')
    expect(addons).not.toContain('Full app access safe mode')
    expect(addons).not.toContain('Grant access and enable')
    expect(row).not.toContain('Review and grant full app access')
    expect(logic).toContain('approveTrustedAddon(addon.manifest.id)')
    expect(logic).toContain('setTrustedSafeMode(false)')
  })

  it('integrates compact real addon controls into the active settings panel', () => {
    const settings = readSettings()
    const addons = readAddons()
    const logic = readAddonLogic()
    const row = readAddonRow()

    expect(settings).toContain("activeSection === 'addons'")
    expect(settings).toContain('<addons-settings-panel />')
    expect(settings).toContain("import AddonsSettingsPanel from './AddonsSettingsPanel.vue'")
    expect(addons).toContain("import { useAddonsSettings } from './useAddonsSettings'")
    expect(logic).toContain('useAddonsStore()')
    expect(logic).toContain('getAddonActions(contributions.value)')
    expect(logic).toContain('installExternalAddon(selected)')
    expect(logic).toContain('setAddonEnabled(addon.manifest.id')
    expect(logic).toContain('runAction(action.id)')
    expect(addons).toContain('<addon-settings-row')
    expect(row).toContain('role="switch"')
    expect(row).toContain("emit('run-action', action)")
    expect(row).toContain("addon.manifest.source === 'external'")
    expect(logic).toContain("log.info('[settings:addons] mounted'")
  })

  it('uses inline destructive confirmation and no unsupported native confirm command', () => {
    const addons = readAddons()
    const logic = readAddonLogic()
    const row = readAddonRow()

    expect(addons).not.toContain('window.confirm')
    expect(logic).not.toContain('window.confirm')
    expect(row).not.toContain('window.confirm')
    expect(row).toContain('Confirm uninstall')
    expect(row).toContain('confirmingUninstall')
    expect(logic).toContain('setCommunityAddonsEnabled(false)')
  })

  it('refreshes the real vault and opens notes produced by addon commands', () => {
    const store = readAddonStore()

    expect(store).toContain('refreshVaultAfterAddonAction')
    expect(store).toContain("import('elephant-front/stores/vaultStore')")
    expect(store).toContain("import('elephant-front/services/elephantnoteClient')")
    expect(store).toContain("elephantnoteClient.directory.list('')")
    expect(store).toContain('vaultStore.openNote(createdEntry)')
    expect(store).toContain("'[addons] action:start'")
    expect(store).toContain("'[addons] action:done'")
  })

  it('removes the dead legacy Addons settings route and component', () => {
    const router = readRouter()

    expect(router).not.toContain("import AddonsSettings from '@/prefComponents/addons'")
    expect(router).not.toContain("path: 'addons'")
    expect(exists('Elephant/frontend/src/renderer/src/prefComponents/addons/index.vue')).toBe(false)
  })

  it('uses semantic controls and exposes real quick-insert preferences', () => {
    const source = readSettings()
    const preferences = readPreferences()
    const sites = readSitesSettings()

    expect(source).toContain('role="switch"')
    expect(source).toContain(':aria-checked="preferences.showEditorFooter"')
    expect(source).toContain(':aria-checked="!preferences.hideQuickInsertHint"')
    expect(source).toContain("setPreference('quickInsertTrigger'")
    expect(source).toContain("setPreference('autoPairBracket'")
    expect(source).toContain("setPreference('spellcheckerEnabled'")
    expect(sites).toContain(':aria-checked="featureEnabled"')
    expect(preferences).toContain('hideQuickInsertHint: false')
    expect(preferences).toContain("quickInsertTrigger: '/'")
    expect(preferences).toContain('autoPairBracket: true')
  })

  it('imports one shared visual primitive layer for AI, Sync and Addons', () => {
    const styles = readSettingsStyles()
    const primitives = readSettingsPrimitives()
    const addons = readAddons()
    const addonStyles = readAddonStyles()
    const row = readAddonRow()

    expect(styles).toContain("@import './settings-primitives.css';")
    expect(styles).toContain('Reusable control chrome lives in settings-primitives.css')
    expect(primitives).toContain('--en-ui-control-height: 34px')
    expect(primitives).toContain('--en-ui-card-radius: 14px')
    expect(primitives).toContain(':where(.en-ai-card, .en-sync-card, .en-addons-card)')
    expect(primitives).toContain(':where(.en-ai-toolbar, .en-sync-toolbar)')
    expect(primitives).toContain('.en-addons-panel .en-primary-button')
    expect(primitives).toContain('.en-addons-panel .en-switch')
    expect(primitives).toContain(':where(.en-ai-badge, .en-provider-state, .en-sync-status')
    expect(addons).toContain('<style scoped src="./addons-settings.css"></style>')
    expect(addonStyles).not.toContain('.en-addons-mode-row .en-switch {')
    expect(row).not.toContain('.en-switch {')
  })

  it('uses one switch geometry for root and nested settings panels', () => {
    const styles = readSettingsStyles()
    const primitives = readSettingsPrimitives()

    expect(styles).not.toContain('.en-settings-panel .en-switch,')
    expect(primitives).toContain('.en-settings-panel .en-switch,')
    expect(primitives).toContain('.en-ai-switch, .en-addons-panel .en-switch')
    expect(primitives).toContain('display: block !important')
    expect(primitives).toContain('transform: translateX(0) !important')
    expect(primitives).toContain('transform: translateX(18px) !important')
    expect(primitives).toContain('.en-settings-panel :deep(.en-ai-switch.small.active > span)')
  })

  it('preserves the exact Import and Sites page structure after extraction', () => {
    const settings = readSettings()
    const imports = readImportSettings()
    const sites = readSitesSettings()
    const importAddon = readImportAddon()
    const sitesAddon = readSitesAddon()

    expect(settings).not.toContain('await elephantnoteClient.imports.googleKeep()')
    expect(settings).not.toContain("toggleFeature('sitePreview')")
    expect(imports).toContain('<section class="en-settings-group">')
    expect(imports).toContain('<div class="en-settings-row">')
    expect(imports).toContain('<div class="en-form-grid">')
    expect(imports).toContain('<div class="en-settings-inline-actions">')
    expect(imports).not.toContain('en-addon-import-settings')
    expect(imports).toContain('await elephantnoteClient.imports.googleKeep()')
    expect(imports).toContain('await elephantnoteClient.sources.ingestUrl')
    expect(imports).toContain('await elephantnoteClient.sources.importRss')
    expect(sites).toContain('<section class="en-settings-group">')
    expect(sites).toContain('<div class="en-settings-row">')
    expect(sites).toContain('<div class="en-settings-inline-actions">')
    expect(sites).not.toContain('en-addon-sites-settings')
    expect(sites).toContain("elephantnoteClient.features.set('sitePreview'")
    expect(sites).toContain('sitePreviewStore.openPreviewExternal')
    expect(sites).toContain('sitePreviewStore.stopPreview()')
    expect(importAddon).toContain('chrome: false')
    expect(sitesAddon).toContain('chrome: false')
    expect(exists('Elephant/frontend/app/components/settings/SystemImportSettings.vue')).toBe(false)
    expect(exists('Elephant/frontend/app/components/settings/SystemSitesSettings.vue')).toBe(false)
  })

  it('keeps Sync navigation at the top and makes retention directly editable', () => {
    const source = readSync()

    expect(source).toContain('class="en-sync-toolbar"')
    expect(source).toContain("activeSyncPage === 'overview'")
    expect(source).toContain("activeSyncPage === 'devices'")
    expect(source).toContain("activeSyncPage === 'conflicts'")
    expect(source).toContain('v-model.number="retentionDays"')
    expect(source).toContain('@click="saveRetention"')
    expect(source).toContain('initialPage: { type: String')
    expect(source).toContain('irohSyncClient.createInvite')
    expect(source).toContain('irohSyncClient.acceptInvite')
    expect(source).toContain('irohSyncClient.run()')
    expect(source).toContain('irohSyncClient.restoreConflict')
    expect(source).toContain('irohSyncClient.deleteConflict')
  })

  it('keeps Codex visually inside AI while its implementation remains addon-owned', () => {
    const ai = readAi()
    const codex = readCodexSettings()
    const addon = readCodexAddon()

    expect(ai).toContain('class="en-ai-toolbar"')
    expect(ai).toContain("addonsStore.getContributions('ai.providers')")
    expect(ai).toContain('data-elephant-addon-settings-slot="ai.providers.after-external"')
    expect(ai).toContain('API usage is billed separately from ChatGPT subscriptions.')
    expect(ai).not.toContain('Addon providers')
    expect(ai).not.toContain('<ChatgptSubscriptionCard')
    expect(ai).not.toContain("invokeCodex('status')")
    expect(ai).not.toContain('codexStatus')
    expect(ai).not.toContain('en-ai-save-state')
    expect(codex).toContain('<ChatgptSubscriptionCard')
    expect(codex).toContain("invokeCodex('status')")
    expect(codex).toContain("invokeCodex('login'")
    expect(codex).toContain("invokeCodex('logout')")
    expect(addon).toContain("ctx.registerContribution('ai.providers'")
    expect(addon).toContain('async getModels()')
    expect(addon).toContain("settingsSection: 'ai'")
    expect(addon).toContain("settingsSubpage: 'provider'")
    expect(addon).toContain("slot: 'ai.providers.after-external'")
    expect(addon).toContain('chrome: false')
    expect(exists('Elephant/frontend/src/renderer/src/addons/builtin/codexConnection.css')).toBe(false)
    expect(exists('Elephant/frontend/app/components/settings/SystemCodexSettings.vue')).toBe(false)
  })

  it('separates common AI controls from advanced technical tuning', () => {
    const source = readAi()

    expect(source).toContain('class="en-ai-advanced"')
    expect(source).toContain('Advanced generation settings')
    expect(source).toContain('Advanced indexing settings')
    expect(source).toContain('role="switch"')
    expect(source).toContain('form.routes.chat.temperature')
    expect(source).toContain('form.routes.embedding.chunkOverlap')
    expect(source).toContain('form.routes.ocr.confidenceThreshold')
  })

  it('keeps AI configuration, provider tests and autosave connected to real clients', () => {
    const source = readAi()

    expect(source).toContain('await elephantnoteClient.ai.getConfig()')
    expect(source).toContain('await elephantnoteClient.ai.setConfig')
    expect(source).toContain('await elephantnoteClient.ai.testConfig')
    expect(source).toContain('await elephantnoteClient.search.rebuild?.()')
    expect(source).toContain("scheduleAutosave('form-watch')")
    expect(source).toContain("saveConfig({ silent: true, reason: 'settings-close' })")
  })
})
