<template>
  <div class="en-sync-panel">
    <section class="en-settings-section stacked">
      <div class="en-sync-heading">
        <div>
          <h3>Peer-to-peer vault sync</h3>
          <p>Encrypted Iroh synchronization for the active vault. No cloud account or shared folder is required.</p>
        </div>
        <span class="en-settings-pill" :class="{ active: pairedDevices.length > 0 }">
          {{ connectionLabel }}
        </span>
      </div>

      <div class="en-sync-summary">
        <div>
          <span>Active vault</span>
          <strong>{{ activeVaultName }}</strong>
          <small>{{ activeVaultPath || 'Open a vault to configure sync.' }}</small>
        </div>
        <div>
          <span>Device identity</span>
          <strong>{{ shortDeviceId }}</strong>
          <small>Iroh EndpointId</small>
        </div>
        <div>
          <span>Last synchronization</span>
          <strong>{{ lastRunLabel }}</strong>
          <small>{{ transferLabel }}</small>
        </div>
      </div>

      <div class="en-settings-actions-row">
        <button type="button" :disabled="loading || !hasVault" @click="refreshAll()">Refresh</button>
        <button type="button" :disabled="loading || !hasVault || !pairedDevices.length" @click="syncNow">
          {{ syncing ? 'Synchronizing…' : 'Sync now' }}
        </button>
        <span class="en-settings-message" :class="{ error: hasError }">{{ statusMessage }}</span>
      </div>
    </section>

    <section class="en-settings-section stacked">
      <div>
        <h3>Pair a device</h3>
        <p>Create an invitation on one device, then paste it on the other device within ten minutes.</p>
      </div>

      <div class="en-pair-grid">
        <div class="en-pair-card">
          <div>
            <strong>1. Create invitation</strong>
            <p>Keep ElephantNote open while the second device accepts the invitation.</p>
          </div>
          <button type="button" :disabled="loading || !hasVault" @click="createInvite">Create invitation</button>
          <template v-if="inviteCode">
            <textarea :value="inviteCode" readonly rows="5" aria-label="Iroh pairing invitation"></textarea>
            <button type="button" @click="copyInvite">{{ copied ? 'Copied' : 'Copy invitation' }}</button>
          </template>
        </div>

        <div class="en-pair-card">
          <div>
            <strong>2. Accept invitation</strong>
            <p>Paste the complete invitation generated by the first device.</p>
          </div>
          <textarea v-model.trim="incomingInvite" rows="5" placeholder="Paste the ElephantNote Iroh invitation here"></textarea>
          <button type="button" :disabled="loading || !hasVault || !incomingInvite" @click="acceptInvite">
            Pair this device
          </button>
        </div>
      </div>

      <div class="en-sync-list">
        <article v-if="!pairedDevices.length" class="en-sync-row muted">
          <div>
            <strong>No paired device</strong>
            <p>Create or accept an invitation to start synchronizing this vault.</p>
          </div>
        </article>
        <article v-for="device in pairedDevices" :key="device.endpointId" class="en-sync-row">
          <div>
            <strong>{{ device.name }}</strong>
            <p>{{ shortId(device.endpointId) }} · last seen {{ formatEpochSeconds(device.lastSeenAt) }}</p>
          </div>
          <span class="en-settings-pill">Verified</span>
        </article>
      </div>
    </section>

    <section class="en-settings-section stacked">
      <div>
        <h3>Conflict retention</h3>
        <p>
          When both devices edit the same file, the newest modification keeps the original path. The older version is
          copied to <code>.conflit/</code> on both devices before synchronization continues.
        </p>
      </div>

      <div class="en-conflict-settings">
        <label>
          <span>Keep conflict copies for</span>
          <div class="en-inline-number">
            <input
              v-model.number="retentionDays"
              type="number"
              :min="conflictSettings.minimumRetentionDays || 1"
              :max="conflictSettings.maximumRetentionDays || 365"
              step="1"
            >
            <span>days</span>
          </div>
        </label>
        <button type="button" :disabled="loading || !hasVault || !validRetention" @click="saveRetention">
          Save retention
        </button>
        <span class="en-settings-message">{{ conflictMessage }}</span>
      </div>

      <p class="en-conflict-note">
        This setting is local to each device. The <code>.conflit/</code> folder is excluded from normal manifests, so
        automatic cleanup never deletes a note or a conflict copy on another device.
      </p>

      <div class="en-sync-list">
        <article v-if="!archiveEntries.length" class="en-sync-row muted">
          <div>
            <strong>No temporary conflict copy</strong>
            <p>Archived versions will appear here and will be removed automatically after {{ retentionDays }} day(s).</p>
          </div>
        </article>
        <article v-for="entry in archiveEntries" :key="entry.path" class="en-sync-row">
          <div>
            <strong>{{ entry.path }}</strong>
            <p>{{ formatBytes(entry.size) }} · archived {{ formatTimestamp(entry.modifiedMs) }}</p>
          </div>
          <span class="en-settings-pill">Temporary</span>
        </article>
      </div>
    </section>

    <section v-if="reportedConflicts.length" class="en-settings-section stacked">
      <div>
        <h3>Conflicts from the last sync</h3>
        <p>The main file contains the most recently modified version. Older versions are available in `.conflit/`.</p>
      </div>
      <div class="en-sync-list">
        <article v-for="conflict in reportedConflicts" :key="conflict.path" class="en-sync-row">
          <div>
            <strong>{{ conflict.path }}</strong>
            <p>Both devices modified this path.</p>
          </div>
          <span class="en-settings-pill">Preserved</span>
        </article>
      </div>
    </section>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { irohSyncClient } from '../../services/irohSyncClient'

const props = defineProps({
  vaults: { type: Array, default: () => [] },
  activeVaultPath: { type: String, default: '' }
})

const status = ref({})
const conflictSettings = ref({
  retentionDays: 3,
  minimumRetentionDays: 1,
  maximumRetentionDays: 365,
  entries: []
})
const retentionDays = ref(3)
const inviteCode = ref('')
const incomingInvite = ref('')
const statusMessage = ref('')
const conflictMessage = ref('')
const loading = ref(false)
const syncing = ref(false)
const copied = ref(false)
let refreshTimer = null

const hasVault = computed(() => Boolean(props.activeVaultPath))
const activeVaultName = computed(() => {
  const active = props.vaults.find((vault) => vault?.path === props.activeVaultPath)
  return active?.name || status.value?.activeVault?.name || 'No active vault'
})
const pairedDevices = computed(() => Array.isArray(status.value?.peers) ? status.value.peers : [])
const archiveEntries = computed(() => Array.isArray(conflictSettings.value?.entries) ? conflictSettings.value.entries : [])
const reportedConflicts = computed(() => Array.isArray(status.value?.conflicts) ? status.value.conflicts : [])
const connectionLabel = computed(() => pairedDevices.value.length
  ? `${pairedDevices.value.length} paired device${pairedDevices.value.length === 1 ? '' : 's'}`
  : 'Not paired')
const shortDeviceId = computed(() => shortId(status.value?.deviceId || 'Unavailable'))
const lastRunLabel = computed(() => formatEpochSeconds(status.value?.lastRunAt, 'Never'))
const transferLabel = computed(() => {
  const files = Number(status.value?.transferredFiles || 0)
  const bytes = Number(status.value?.transferredBytes || 0)
  return files ? `${files} file${files === 1 ? '' : 's'} · ${formatBytes(bytes)}` : 'No transfer recorded'
})
const validRetention = computed(() => {
  const value = Number(retentionDays.value)
  const minimum = Number(conflictSettings.value?.minimumRetentionDays || 1)
  const maximum = Number(conflictSettings.value?.maximumRetentionDays || 365)
  return Number.isInteger(value) && value >= minimum && value <= maximum
})
const hasError = computed(() => Boolean(status.value?.lastError))

const shortId = (value) => {
  const text = String(value || '')
  if (text.length <= 20) return text
  return `${text.slice(0, 10)}…${text.slice(-8)}`
}

const formatEpochSeconds = (value, fallback = 'Unknown') => {
  const seconds = Number(value)
  if (!Number.isFinite(seconds) || seconds <= 0) return fallback
  return new Date(seconds * 1000).toLocaleString()
}

const formatTimestamp = (value) => {
  const milliseconds = Number(value)
  if (!Number.isFinite(milliseconds) || milliseconds <= 0) return 'unknown time'
  return new Date(milliseconds).toLocaleString()
}

const formatBytes = (value) => {
  const bytes = Number(value || 0)
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B'
  const units = ['B', 'KiB', 'MiB', 'GiB']
  const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1)
  const amount = bytes / (1024 ** index)
  return `${amount >= 10 || index === 0 ? amount.toFixed(0) : amount.toFixed(1)} ${units[index]}`
}

const errorMessage = (error, fallback) => error instanceof Error ? error.message : fallback

const loadStatus = async () => {
  status.value = await irohSyncClient.status()
  statusMessage.value = status.value?.lastError || ''
}

const loadConflictSettings = async () => {
  const result = await irohSyncClient.conflictSettings()
  conflictSettings.value = result || conflictSettings.value
  retentionDays.value = Number(result?.retentionDays || 3)
  if (Number(result?.deletedFiles || 0) > 0) {
    conflictMessage.value = `${result.deletedFiles} expired conflict file(s) removed.`
  }
}

const refreshAll = async (silent = false) => {
  if (!hasVault.value || (loading.value && !silent)) return
  if (!silent) loading.value = true
  try {
    await Promise.all([loadStatus(), loadConflictSettings()])
  } catch (error) {
    statusMessage.value = errorMessage(error, 'Unable to load Iroh synchronization status.')
  } finally {
    if (!silent) loading.value = false
  }
}

const createInvite = async () => {
  if (!hasVault.value || loading.value) return
  loading.value = true
  statusMessage.value = 'Creating a secure one-time invitation…'
  try {
    const result = await irohSyncClient.createInvite({ deviceName: activeVaultName.value })
    inviteCode.value = String(result?.manualCode || result?.qrPayload || '')
    copied.value = false
    statusMessage.value = inviteCode.value
      ? 'Invitation created. Paste it on the second device within ten minutes.'
      : 'Invitation created.'
  } catch (error) {
    statusMessage.value = errorMessage(error, 'Unable to create an Iroh invitation.')
  } finally {
    loading.value = false
  }
}

const copyInvite = async () => {
  if (!inviteCode.value) return
  try {
    await navigator.clipboard.writeText(inviteCode.value)
    copied.value = true
  } catch {
    copied.value = false
    statusMessage.value = 'Clipboard access failed. Select and copy the invitation manually.'
  }
}

const acceptInvite = async () => {
  if (!incomingInvite.value || !hasVault.value || loading.value) return
  loading.value = true
  statusMessage.value = 'Pairing with the remote Iroh device…'
  try {
    const result = await irohSyncClient.acceptInvite(incomingInvite.value)
    status.value = result?.status || await irohSyncClient.status()
    incomingInvite.value = ''
    statusMessage.value = 'Device paired. You can synchronize now.'
    await loadConflictSettings()
  } catch (error) {
    statusMessage.value = errorMessage(error, 'Unable to accept this invitation.')
  } finally {
    loading.value = false
  }
}

const syncNow = async () => {
  if (!pairedDevices.value.length || !hasVault.value || loading.value) return
  loading.value = true
  syncing.value = true
  statusMessage.value = 'Comparing manifests and transferring changed files…'
  try {
    status.value = await irohSyncClient.run()
    statusMessage.value = status.value?.lastError || 'Synchronization finished.'
    await loadConflictSettings()
  } catch (error) {
    statusMessage.value = errorMessage(error, 'Synchronization failed.')
  } finally {
    syncing.value = false
    loading.value = false
  }
}

const saveRetention = async () => {
  if (!validRetention.value || !hasVault.value || loading.value) return
  loading.value = true
  conflictMessage.value = 'Saving local conflict retention…'
  try {
    const result = await irohSyncClient.setConflictRetentionDays(retentionDays.value)
    conflictSettings.value = result
    retentionDays.value = Number(result?.retentionDays || retentionDays.value)
    conflictMessage.value = Number(result?.deletedFiles || 0) > 0
      ? `Saved. ${result.deletedFiles} expired conflict file(s) removed.`
      : 'Retention saved for this device.'
  } catch (error) {
    conflictMessage.value = errorMessage(error, 'Unable to save conflict retention.')
  } finally {
    loading.value = false
  }
}

watch(() => props.activeVaultPath, () => {
  inviteCode.value = ''
  incomingInvite.value = ''
  refreshAll()
})

onMounted(() => {
  refreshAll()
  refreshTimer = window.setInterval(() => {
    if (!loading.value && hasVault.value) refreshAll(true)
  }, 5000)
})

onBeforeUnmount(() => {
  if (refreshTimer) window.clearInterval(refreshTimer)
})
</script>

<style scoped>
.en-sync-panel { display: flex; flex-direction: column; gap: 18px; }
.en-sync-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; }
.en-settings-pill.active { border-color: var(--en-active-border, #2563eb); color: var(--en-active-text, #2563eb); }
.en-sync-summary { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; }
.en-sync-summary > div { display: flex; flex-direction: column; gap: 5px; min-width: 0; padding: 14px; border: 1px solid var(--en-border, #c5cfdd); border-radius: 14px; background: var(--en-surface, #fff); }
.en-sync-summary span, .en-sync-summary small { color: var(--en-muted, #475467); }
.en-sync-summary strong, .en-sync-summary small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.en-pair-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }
.en-pair-card { display: flex; flex-direction: column; align-items: stretch; gap: 12px; padding: 14px; border: 1px solid var(--en-border, #c5cfdd); border-radius: 14px; background: var(--en-surface, #fff); }
.en-pair-card p { margin: 5px 0 0; color: var(--en-muted, #475467); }
.en-pair-card textarea { width: 100%; min-height: 112px; resize: vertical; box-sizing: border-box; font: 12px/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; }
.en-sync-list { display: flex; flex-direction: column; gap: 12px; }
.en-sync-row { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 14px; border: 1px solid var(--en-border, #c5cfdd); border-radius: 14px; background: var(--en-surface, #fff); }
.en-sync-row.muted { opacity: 0.72; }
.en-sync-row p { margin: 4px 0 0; color: var(--en-muted, #475467); word-break: break-word; }
.en-conflict-settings { display: flex; align-items: end; gap: 12px; flex-wrap: wrap; }
.en-conflict-settings label { display: flex; flex-direction: column; gap: 7px; }
.en-inline-number { display: flex; align-items: center; gap: 8px; }
.en-inline-number input { width: 96px; }
.en-conflict-note { margin: 0; padding: 12px 14px; border-radius: 12px; background: var(--en-card, #f2f4f7); color: var(--en-muted, #475467); }
.en-settings-message.error { color: #b42318; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
@media (max-width: 820px) {
  .en-sync-summary, .en-pair-grid { grid-template-columns: 1fr; }
  .en-sync-heading, .en-sync-row { align-items: flex-start; flex-direction: column; }
}
</style>
