export const normalizePastedHtml = (html = '') => String(html)
  .replace(/<!--[^]*?-->/g, '')
  .replace(/\sclass="Mso[^"]*"/g, '')
  .replace(/\sstyle="[^"]*mso-[^"]*"/gi, '')
  .replace(/\sdata-block-id="[^"]*"/g, '')
  .replace(/\sdata-notion-[^=]+="[^"]*"/g, '')
  .replace(/<meta[^>]*>/gi, '')
  .replace(/<span[^>]*>/gi, '')
  .replace(/<\/span>/gi, '')

export const sanitizePastedHtml = (html = '') => normalizePastedHtml(html)
  .replace(/<script[\s\S]*?<\/script>/gi, '')
  .replace(/<style[\s\S]*?<\/style>/gi, '')
  .replace(/\son[a-z]+="[^"]*"/gi, '')
  .replace(/javascript:/gi, 'blocked-javascript:')

export const pastedHtmlToMarkdown = (html = '') => sanitizePastedHtml(html)
  .replace(/<h([1-6])[^>]*>([\s\S]*?)<\/h\1>/gi, (_, level, text) => `${'#'.repeat(Number(level))} ${stripTags(text)}\n\n`)
  .replace(/<li[^>]*>\s*<input[^>]*checked[^>]*>\s*([\s\S]*?)<\/li>/gi, (_, text) => `- [x] ${stripTags(text)}\n`)
  .replace(/<li[^>]*>\s*<input[^>]*>\s*([\s\S]*?)<\/li>/gi, (_, text) => `- [ ] ${stripTags(text)}\n`)
  .replace(/<li[^>]*>([\s\S]*?)<\/li>/gi, (_, text) => `- ${stripTags(text)}\n`)
  .replace(/<img[^>]*alt="([^"]*)"[^>]*src="([^"]*)"[^>]*>/gi, (_, alt, src) => `![${alt}](${src})`)
  .replace(/<a[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/gi, (_, href, text) => `[${stripTags(text)}](${href})`)
  .replace(/<tr[^>]*>([\s\S]*?)<\/tr>/gi, (_, row) => `| ${[...row.matchAll(/<t[hd][^>]*>([\s\S]*?)<\/t[hd]>/gi)].map((m) => stripTags(m[1])).join(' | ')} |\n`)
  .replace(/<p[^>]*>([\s\S]*?)<\/p>/gi, (_, text) => `${stripTags(text)}\n\n`)
  .replace(/<br\s*\/?>/gi, '\n')
  .replace(/<[^>]+>/g, '')
  .replace(/\n{3,}/g, '\n\n')
  .trim()

export const clipboardPayloadToMarkdown = ({ html = '', text = '' } = {}) => html ? pastedHtmlToMarkdown(html) : String(text || '')

export const copyMarkdownAndHtml = (markdown = '', renderHtml = (value) => value) => ({ markdown, html: renderHtml(markdown) })

const stripTags = (html = '') => html.replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').trim()
