use serde_json::{json, Value};
use std::{fs, path::{Path, PathBuf}, time::{SystemTime, UNIX_EPOCH}};
use tauri::{AppHandle, Manager};

type R<T> = Result<T, String>;
const META: &str = ".elephantnote";
const CFG: &str = "tauri-vaults.json";

fn ts() -> String { SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs().to_string()).unwrap_or_else(|_| "0".into()) }
fn sl(s: impl AsRef<str>) -> String { s.as_ref().replace('\\', "/") }
fn bn(p: impl AsRef<Path>) -> String { p.as_ref().file_name().and_then(|n| n.to_str()).unwrap_or("Personal").to_string() }
fn no_md(s: &str) -> String { s.strip_suffix(".md").or_else(|| s.strip_suffix(".MD")).unwrap_or(s).to_string() }
fn id(s: &str) -> String { let mut o=String::new(); let mut d=false; for c in s.trim().to_lowercase().chars(){ if c.is_ascii_alphanumeric(){o.push(c);d=false}else if !d{o.push('-');d=true}} let x=o.trim_matches('-').to_string(); if x.is_empty(){"vault".into()}else{x} }
fn rel(s: &str) -> String { s.replace('\\', "/").split('/').filter(|p| !p.is_empty() && *p != "." && *p != "..").collect::<Vec<_>>().join("/") }
fn inside(root: &str, r: &str) -> PathBuf { let r=rel(r); if r.is_empty(){PathBuf::from(root)}else{PathBuf::from(root).join(r)} }
fn wp(root: &str, f: &str) -> PathBuf { PathBuf::from(root).join(META).join(f) }
fn cp(app: &AppHandle) -> R<PathBuf> { let d=app.path().app_config_dir().map_err(|e| e.to_string())?; fs::create_dir_all(&d).map_err(|e| e.to_string())?; Ok(d.join(CFG)) }
fn rc(app: &AppHandle) -> R<Value> { let p=cp(app)?; if !p.exists(){return Ok(json!({"vaults":[],"activeVaultId":null}))} let raw=fs::read_to_string(p).map_err(|e| e.to_string())?; Ok(serde_json::from_str(&raw).unwrap_or_else(|_| json!({"vaults":[],"activeVaultId":null}))) }
fn wc(app: &AppHandle, c: &Value) -> R<()> { fs::write(cp(app)?, serde_json::to_string_pretty(c).map_err(|e| e.to_string())?).map_err(|e| e.to_string()) }
fn av(c: &Value) -> Option<Value> { let id=c.get("activeVaultId")?.as_str()?; c.get("vaults")?.as_array()?.iter().find(|v| v.get("id").and_then(Value::as_str)==Some(id)).cloned() }
fn ws(root:&str)->Value{json!({"version":1,"vaultName":bn(root),"sidebar":[{"id":"getting-started","title":"Getting started","type":"folder","path":"Getting Started","collapsed":false}]})}
fn rj(p:PathBuf,f:Value)->Value{fs::read_to_string(p).ok().and_then(|r|serde_json::from_str(&r).ok()).unwrap_or(f)}
fn wj(p:PathBuf,v:&Value)->R<()> { if let Some(pa)=p.parent(){fs::create_dir_all(pa).map_err(|e|e.to_string())?} fs::write(p,serde_json::to_string_pretty(v).map_err(|e|e.to_string())?).map_err(|e|e.to_string()) }
fn ensure_json(p:PathBuf,v:Value)->R<()> { if p.exists(){return Ok(())} wj(p,&v) }
fn init(root:&str)->R<Value>{fs::create_dir_all(PathBuf::from(root).join(META)).map_err(|e|e.to_string())?;fs::create_dir_all(PathBuf::from(root).join("Getting Started")).map_err(|e|e.to_string())?;ensure_json(wp(root,"workspace.json"),ws(root))?;ensure_json(wp(root,"index.json"),json!({"version":1,"updatedAt":ts(),"entries":[]}))?;ensure_json(wp(root,"calendar.json"),json!({"version":1,"updatedAt":ts(),"events":[]}))?;ensure_json(wp(root,"sources.json"),json!({"version":1,"updatedAt":ts(),"sources":[]}))?;ensure_json(wp(root,"wiki.json"),json!({"version":1,"updatedAt":ts(),"records":[]}))?;let w=PathBuf::from(root).join("Getting Started/Welcome.md");if !w.exists(){fs::write(w,format!("---\ntitle: \"Welcome\"\ntype: \"note\"\ntags: [\"getting-started\"]\ncreatedAt: \"{}\"\nupdatedAt: \"{}\"\n---\n\n# Welcome to ElephantNote\n",ts(),ts())).map_err(|e|e.to_string())?} Ok(rj(wp(root,"workspace.json"),ws(root)))}
fn ignored(n:&str)->bool{n==META||n==".git"||n=="node_modules"||n.starts_with('.')||n.ends_with('~')||n.ends_with(".tmp")}
fn mt(p:&Path)->String{fs::metadata(p).and_then(|m|m.modified()).ok().and_then(|t|t.duration_since(UNIX_EPOCH).ok()).map(|d|d.as_secs().to_string()).unwrap_or_else(ts)}
fn meta(md:&str,fb:&str)->Value{let mut title=String::new();let mut tags=Vec::<String>::new();if let Some(rest)=md.strip_prefix("---"){if let Some(end)=rest.find("\n---"){for l in rest[..end].lines(){if let Some((k,v))=l.split_once(':'){if k.trim()=="title"{title=v.trim().trim_matches('"').into()} if k.trim()=="tags"{tags=v.trim().trim_matches(&['[',']'][..]).split(',').map(|x|x.trim().trim_matches('"').trim_start_matches('#').to_string()).filter(|x|!x.is_empty()).collect()}}}}} let body=if md.starts_with("---"){md.splitn(3,"---").nth(2).unwrap_or(md)}else{md};if title.is_empty(){title=body.lines().find_map(|l|l.strip_prefix("# ").map(|x|x.trim().to_string())).unwrap_or_else(||no_md(fb))}let excerpt=body.lines().map(|l|l.trim().trim_start_matches('#').trim()).filter(|l|!l.is_empty()).take(3).collect::<Vec<_>>().join(" ");json!({"title":title,"type":"note","tags":tags,"createdAt":"","updatedAt":"","excerpt":excerpt,"coverImage":""})}
fn list(v:&Value,r:&str)->R<Vec<Value>>{let root=v.get("path").and_then(Value::as_str).ok_or("invalid vault")?;let mut out=Vec::new();for it in fs::read_dir(inside(root,r)).map_err(|e|e.to_string())?{let it=it.map_err(|e|e.to_string())?;let name=it.file_name().to_string_lossy().to_string();if ignored(&name){continue}let p=it.path();let st=fs::metadata(&p).map_err(|e|e.to_string())?;let cr=rel(&format!("{r}/{name}"));if st.is_dir(){let n=fs::read_dir(&p).ok().map(|c|c.filter_map(Result::ok).filter(|x|x.file_name().to_string_lossy().to_lowercase().ends_with(".md")).count()).unwrap_or(0);out.push(json!({"kind":"folder","title":name,"path":cr,"noteCount":n,"updatedAt":mt(&p),"type":"folder","tags":[],"createdAt":"","excerpt":"","coverImage":""}))}else if st.is_file()&&name.to_lowercase().ends_with(".md"){let md=fs::read_to_string(&p).unwrap_or_default();let mut e=meta(&md,&name);e["kind"]=json!("note");e["path"]=json!(cr);e["filename"]=json!(name);e["updatedAt"]=json!(mt(&p));out.push(e)}}Ok(out)}
fn payload(app:&AppHandle,v:Option<Value>)->R<Value>{let c=rc(app)?;if let Some(v)=v{let root=v.get("path").and_then(Value::as_str).unwrap_or("");Ok(json!({"vaults":c.get("vaults").cloned().unwrap_or(json!([])),"activeVaultId":c.get("activeVaultId").cloned().unwrap_or(Value::Null),"activeVault":v,"workspace":init(root)?,"entries":list(&v,"")?}))}else{Ok(json!({"vaults":c.get("vaults").cloned().unwrap_or(json!([])),"activeVaultId":c.get("activeVaultId").cloned().unwrap_or(Value::Null),"activeVault":null,"workspace":null,"entries":[]}))}}
fn active(app:&AppHandle)->R<Value>{av(&rc(app)?).ok_or_else(||"No active ElephantNote vault.".to_string())}
fn upsert(app:&AppHandle,path:String)->R<Value>{let mut c=rc(app)?;let abs=sl(PathBuf::from(path).to_string_lossy());let arr=c.get_mut("vaults").and_then(Value::as_array_mut).ok_or("invalid config")?;if let Some(i)=arr.iter().position(|v|v.get("path").and_then(Value::as_str)==Some(abs.as_str())){let id=arr[i].get("id").and_then(Value::as_str).unwrap_or("vault").to_string();arr[i]["lastOpenedAt"]=json!(ts());let v=arr[i].clone();c["activeVaultId"]=json!(id);wc(app,&c)?;return Ok(v)}let name=bn(&abs);let mut vid=id(&name);let b=vid.clone();let mut n=2;while arr.iter().any(|v|v.get("id").and_then(Value::as_str)==Some(vid.as_str())){vid=format!("{b}-{n}");n+=1}let v=json!({"id":vid,"name":name,"path":abs,"icon":"","lastOpenedAt":ts()});c["activeVaultId"]=v.get("id").cloned().unwrap_or(Value::Null);c.get_mut("vaults").and_then(Value::as_array_mut).unwrap().push(v.clone());wc(app,&c)?;Ok(v)}
fn next(dir:&Path,name:&str)->String{if !dir.join(name).exists(){return name.into()}let ext=Path::new(name).extension().and_then(|e|e.to_str()).map(|e|format!(".{e}")).unwrap_or_default();let stem=name.strip_suffix(&ext).unwrap_or(name);let mut i=2;loop{let c=format!("{stem} {i}{ext}");if !dir.join(&c).exists(){return c}i+=1}}
fn scan(root:&Path,cur:&Path,out:&mut Vec<(String,PathBuf,String)>)->R<()> {for it in fs::read_dir(cur).map_err(|e|e.to_string())?{let it=it.map_err(|e|e.to_string())?;let name=it.file_name().to_string_lossy().to_string();if ignored(&name){continue}let p=it.path();let st=fs::metadata(&p).map_err(|e|e.to_string())?;if st.is_dir(){scan(root,&p,out)?}else if st.is_file()&&name.to_lowercase().ends_with(".md"){out.push((sl(p.strip_prefix(root).unwrap_or(&p).to_string_lossy()),p.clone(),fs::read_to_string(&p).unwrap_or_default()))}}Ok(())}

#[tauri::command] pub fn tauri_vaults_get(app:AppHandle)->R<Value>{let c=rc(&app)?;payload(&app,av(&c))}
#[tauri::command] pub fn tauri_vaults_select_path(app:AppHandle,vault_path:String)->R<Value>{let v=upsert(&app,vault_path)?;payload(&app,Some(v))}
#[tauri::command] pub fn tauri_vaults_set_active(app:AppHandle,vault_id:String)->R<Value>{let mut c=rc(&app)?;c["activeVaultId"]=json!(vault_id);let v=av(&c);wc(&app,&c)?;payload(&app,v)}
#[tauri::command] pub fn tauri_vaults_set_icon(app:AppHandle,vault_id:String,icon:String)->R<Value>{let mut c=rc(&app)?;if let Some(a)=c.get_mut("vaults").and_then(Value::as_array_mut){for v in a{if v.get("id").and_then(Value::as_str)==Some(vault_id.as_str()){v["icon"]=json!(icon)}}}let v=av(&c);wc(&app,&c)?;payload(&app,v)}
#[tauri::command] pub fn tauri_vaults_set_name(app:AppHandle,vault_id:String,name:String)->R<Value>{let mut c=rc(&app)?;if let Some(a)=c.get_mut("vaults").and_then(Value::as_array_mut){for v in a{if v.get("id").and_then(Value::as_str)==Some(vault_id.as_str()){v["name"]=json!(name.trim())}}}let v=av(&c);wc(&app,&c)?;payload(&app,v)}
#[tauri::command] pub fn tauri_vaults_remove(app:AppHandle,vault_id:String)->R<Value>{let mut c=rc(&app)?;if let Some(a)=c.get_mut("vaults").and_then(Value::as_array_mut){a.retain(|v|v.get("id").and_then(Value::as_str)!=Some(vault_id.as_str()))}if c.get("activeVaultId").and_then(Value::as_str)==Some(vault_id.as_str()){c["activeVaultId"]=c.get("vaults").and_then(Value::as_array).and_then(|a|a.first()).and_then(|v|v.get("id")).cloned().unwrap_or(Value::Null)}let v=av(&c);wc(&app,&c)?;payload(&app,v)}
#[tauri::command] pub fn tauri_directory_list(app:AppHandle,relative_path:Option<String>)->R<Vec<Value>>{list(&active(&app)?,relative_path.as_deref().unwrap_or(""))}
#[tauri::command] pub fn tauri_notes_create(app:AppHandle,relative_path:Option<String>,filename:Option<String>,title:Option<String>)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let r=relative_path.unwrap_or_default();let d=inside(root,&r);fs::create_dir_all(&d).map_err(|e|e.to_string())?;let f=filename.filter(|x|!x.trim().is_empty()).unwrap_or_else(||next(&d,"Untitled.md"));let p=d.join(&f);let t=title.filter(|x|!x.trim().is_empty()).unwrap_or_else(||no_md(&f));if !p.exists(){fs::write(&p,format!("---\ntitle: \"{}\"\ntype: \"note\"\ntags: []\ncreatedAt: \"{}\"\nupdatedAt: \"{}\"\n---\n\n# {}\n",t.replace('"',"\\\""),ts(),ts(),t)).map_err(|e|e.to_string())?}Ok(json!({"note":{"path":rel(&format!("{r}/{f}")),"fullPath":p.to_string_lossy(),"title":t},"entries":list(&v,&r)?}))}
#[tauri::command] pub fn tauri_folders_create(app:AppHandle,relative_path:Option<String>)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let r=relative_path.unwrap_or_default();let d=inside(root,&r);fs::create_dir_all(&d).map_err(|e|e.to_string())?;let f=next(&d,"New Folder");let p=d.join(&f);fs::create_dir_all(&p).map_err(|e|e.to_string())?;Ok(json!({"folder":{"path":rel(&format!("{r}/{f}")),"fullPath":p.to_string_lossy()},"entries":list(&v,&r)?}))}
#[tauri::command] pub fn tauri_sidebar_attach(app:AppHandle,relative_path:String,title:Option<String>,entry_type:Option<String>)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let p=rel(&relative_path);let mut w=rj(wp(root,"workspace.json"),ws(root));let mut s=w.get("sidebar").and_then(Value::as_array).cloned().unwrap_or_default();s.retain(|e|e.get("path").and_then(Value::as_str)!=Some(p.as_str()));s.push(json!({"id":id(&p),"title":title.unwrap_or_else(||no_md(&bn(&p))),"type":entry_type.unwrap_or_else(||if p.ends_with(".md"){"note".into()}else{"folder".into()}),"path":p,"collapsed":false}));w["sidebar"]=json!(s);wj(wp(root,"workspace.json"),&w)?;Ok(json!({"workspace":w,"entries":list(&v,"")?}))}
#[tauri::command] pub fn tauri_sidebar_detach(app:AppHandle,relative_path:String)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let p=rel(&relative_path);let mut w=rj(wp(root,"workspace.json"),ws(root));let mut s=w.get("sidebar").and_then(Value::as_array).cloned().unwrap_or_default();s.retain(|e|e.get("path").and_then(Value::as_str)!=Some(p.as_str()));w["sidebar"]=json!(s);wj(wp(root,"workspace.json"),&w)?;Ok(json!({"workspace":w,"entries":list(&v,"")?}))}
#[tauri::command] pub fn tauri_entries_rename(app:AppHandle,relative_path:String,title:String)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let src=inside(root,&relative_path);let parent=src.parent().ok_or("Cannot rename vault root")?;let safe=title.trim().replace('/',"-").replace('\\',"-");let ext=if src.is_file()&&src.extension().is_some()&&Path::new(&safe).extension().is_none(){src.extension().and_then(|e|e.to_str()).map(|e|format!(".{e}")).unwrap_or_default()}else{String::new()};fs::rename(&src,parent.join(format!("{safe}{ext}"))).map_err(|e|e.to_string())?;payload(&app,Some(v))}
#[tauri::command] pub fn tauri_entries_move(app:AppHandle,relative_path:String,target_directory_path:Option<String>)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let src=inside(root,&relative_path);let dst=inside(root,target_directory_path.as_deref().unwrap_or(""));fs::create_dir_all(&dst).map_err(|e|e.to_string())?;let name=src.file_name().ok_or("Invalid source path")?;fs::rename(&src,dst.join(name)).map_err(|e|e.to_string())?;payload(&app,Some(v))}
#[tauri::command] pub fn tauri_entries_delete(app:AppHandle,relative_path:String)->R<Value>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");let t=inside(root,&relative_path);if t.is_dir(){fs::remove_dir_all(&t).map_err(|e|e.to_string())?}else if t.is_file(){fs::remove_file(&t).map_err(|e|e.to_string())?}payload(&app,Some(v))}
#[tauri::command] pub fn tauri_calendar_list(app:AppHandle)->R<Vec<Value>>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");Ok(rj(wp(root,"calendar.json"),json!({"events":[]})).get("events").and_then(Value::as_array).cloned().unwrap_or_default())}
#[tauri::command] pub fn tauri_sources_list(app:AppHandle)->R<Vec<Value>>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");Ok(rj(wp(root,"sources.json"),json!({"sources":[]})).get("sources").and_then(Value::as_array).cloned().unwrap_or_default())}
#[tauri::command] pub fn tauri_wiki_list(app:AppHandle)->R<Vec<Value>>{let v=active(&app)?;let root=v.get("path").and_then(Value::as_str).unwrap_or("");Ok(rj(wp(root,"wiki.json"),json!({"records":[]})).get("records").and_then(Value::as_array).cloned().unwrap_or_default())}
#[tauri::command] pub fn tauri_search_query(app:AppHandle,params:Option<Value>)->R<Value>{let v=active(&app)?;let q=params.and_then(|x|x.get("query").or_else(||x.get("q")).and_then(Value::as_str).map(str::to_string)).unwrap_or_default().to_lowercase();if q.trim().is_empty(){return Ok(json!({"results":[]}))}let root=PathBuf::from(v.get("path").and_then(Value::as_str).unwrap_or(""));let mut notes=Vec::new();scan(&root,&root,&mut notes)?;let mut res=Vec::new();for (r,p,md) in notes{if md.to_lowercase().contains(&q)||r.to_lowercase().contains(&q){let m=meta(&md,&r);res.push(json!({"path":r,"fullPath":p.to_string_lossy(),"title":m.get("title").cloned().unwrap_or(json!("Untitled")),"tags":m.get("tags").cloned().unwrap_or(json!([])),"excerpt":m.get("excerpt").cloned().unwrap_or(json!("")),"score":1}))}}Ok(json!({"results":res}))}
#[tauri::command] pub fn tauri_search_status(app:AppHandle)->R<Value>{Ok(json!({"enabled":true,"runtime":"tauri-rust","activeVault":av(&rc(&app)?)}))}
#[tauri::command] pub fn tauri_sync_status(app:AppHandle)->R<Value>{Ok(json!({"runtime":"tauri-rust","activeVault":av(&rc(&app)?),"queued":0,"running":false,"lastRunAt":null}))}
#[tauri::command] pub fn tauri_sync_enqueue(operation:String,payload:Option<Value>)->R<Value>{Ok(json!({"queued":false,"operation":operation,"payload":payload,"reason":"queue-not-enabled-yet"}))}
#[tauri::command] pub fn tauri_sync_run(app:AppHandle,payload_by_operation:Option<Value>)->R<Value>{Ok(json!({"ok":true,"runtime":"tauri-rust","activeVault":av(&rc(&app)?),"payload":payload_by_operation}))}
